name: Auto Delete update/assetlist Branch
on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'approved'
    
    runs-on: ubuntu-latest
    - name: Delete Merged Branches
      uses: imajeetyadav/delete-merged-branches@v1
      with:
        branch: update/assetlist
