name: Generate Asset list via Node.js
on:
  workflow_dispatch:
    inputs:
      chain_id_selection:
        description: 'Chain ID Selection'
        required: true
        default: 'osmosis-1'
        type: choice
        options:
          - osmosis-1
          - juno-1
          - kaiyo-1
      chain_name_selection:
        description: 'Chain NAME Selection'
        default: 'osmosis'
        type: choice
        options:
          - osmosis
          - juno
          - kujira
jobs:
  generate_assetlist:
    name: Generate Assetlist with Code
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true

      - name: Git Submodule Update
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm ci

      - name: Run code to Generate Asset list
        working-directory: ./.github/workflows/utility
        run: CHAIN_ID=${{ inputs.chain_id_selection }} CHAIN_NAME=${{ inputs.chain_name_selection }} node generate_assetlist.mjs

      - name: Run ESLint
        working-directory: ./osmosis-1
        run: npx eslint --ext *.json --fix

      - name: Add Commit Push
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          add_timestamp: false
          commit_prefix: "[🔃][AUTO] "
          commit_message: "${{ inputs.chain_id_selection }}.assetlist.json Update."
          force: true
          target_branch: update/assetlist

      - name: Create Auto PR
        uses: devops-infra/action-pull-request@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: update/assetlist
          target_branch: main
          reviewer: ToggLeTek
          assignee: ToggLeTek
          title: "[🔃][AUTO] Pulling ${{ github.ref }} into main"
          body: "## :robot: **Automated PR for Updated Asset list** \n *Automatic checks should have engaged*, please ensure the files are accurate. Thank you!"
