name: Generate Assetlist
on:
  workflow_dispatch:
    inputs:
      chain_id_selection:
        description: 'Chain ID Selection'
        required: true
        default: 'osmosis-1'
        type: choice
        options:
          - osmosis-1
          - juno-1
      chain_name_selection:
        description: 'Chain NAME Selection'
        default: 'osmosis'
        type: choice
        options:
          - osmosis
          - juno
jobs:
  generate_assetlist:
    name: Generate Assetlist
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
    
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
          
      - name: Git Sumbodule Update
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
          
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19
          
      - name: Run code to Generate Assetlist
        working-directory: ./.github/workflows/utility
        run: CHAIN_ID=${{ inputs.chain_id_selection }} CHAIN_NAME=${{ inputs.chain_name_selection }} node generate_assetlist.mjs
      
      - name: Add Commit Push
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          add_timestamp: false
          commit_prefix: "[AUTO] "
          commit_message: "${{ inputs.chain_id_selection }}.assetlist.json Update"
          force: true
          target_branch: update/assetlist
      
      - name: Create A PR
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update/assetlist
          base: main
          title: ${{ inputs.chain_id_selection }}.assetlist.json Auto Update
          body: "**Automated pull request**"
          assignees: ToggLeTek
