on:
  pull_request:
    branches:
      - main
name: PR Validate Zone Data
jobs:
  validate_assetlists:
    name: Validate zone
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate Zone schema
        uses: mcandeia/json-schema-validator@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json_schema: ./zone.schema.json
          json_path_pattern: .*zone.json$
