on:
  pull_request:
    branches:
      - main
name: Pull request workflow
jobs:
  validate_assetlists:
    name: Validate assetlists
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate Asset List schema
        uses: mcandeia/json-schema-validator@v1.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json_schema: ./assetlist.schema.json
          json_path_pattern: .*assetlist.json$
